---
title: "stat0019_ica"
author: '19038456 20019563 22095670'
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

Four parameters $p1$, $p2$, $l0$, and $l1$ are used in defining the average costs $\mu_{ct}$, the average QALYs $\mu_{et}$, and the monetary net benefit $nb_t$, where $p1$ and $p2$ are the probability of having severe complications in the placebo group and the active treatment group, respectively; $l0$ and $l1$ are the length of inpatient days for patients without and with severe complications respectively.

$\mu_{et}$ is the average of the effectiveness conditional on the treatment group $t$, where $t \in \{1=\text{status quo} = \text{no prophylaxis},2= \text{active intervention} = \text{antibiotics prophylaxis}\}$. It is the sum of QALYs during inpatient period and the period with full health in one year. By dividing 365, the time unit is converted into years.

$\mu_{ct}$ is the average of the cost conditional on the treatment group $t$, in which $t \in \{1=\text{status quo} = \text{no prophylaxis},2= \text{active intervention} = \text{antibiotics prophylaxis}\}$. For the treatment group, the costs in the one-year period consist of variable costs such as the costs of inpatient stays, and fixed costs such as the acquisition and administration costs of using antibiotics. For the placebo group, only costs of inpatient stays are included.

For $t = 1 =\text{status quo} = \text{no prophylaxis}$:

$$
\begin{align}
\mu_{e1} &= [p1 * (l1 * 0.0013151 + (365 - l1)) + (1 - p1) * (l0 * 0.0025205 + (365 - l0))]/365 \\
\mu_{c1} &= p1 * (168.19 * l1) + (1 - p1) * (113.61 * l0)
\end{align}
$$

For $t = 2 = \text{active intervention}= \text{antibiotics prophylaxis}$:

$$
\begin{align}
\mu_{e2} &= [p2 * (l1 * 0.0013151 + (365 - l1)) + (1 - p2) * (l0 * 0.0025205 + (365 - l0))]/365 \\
\mu_{c2} &= p2 * (168.19 * l1 + 201.47) + (1 - p2) * (113.61 * l0 + 201.47) 
\end{align}
$$

Monetary Net Benefit is $u(e,c;t) = nb_t = k\mu_{et} - \mu_{ct}$. $k$ is the "willingness to pay", which is the maximum amount people are willing to contribute in order to gain one extra unit of QALY. If $k$ exceeds the incremental cost-effectiveness ratios (ICER), the decision makers will implement the intervention; if $k$ is less than the ICER, the intervention will not be adopted. The monetary net benefit $nb_t$ represents the value of an intervention in monetary terms when a willingness to pay threshold for a unit of benefit (for example a measure of health outcome or QALY) and cost are known.

When $t = 1$:

$$
\begin{align}
u(e,c;t) &= nb_t = k\mu_{et} - \mu_{ct} \\
u(e,c;t) &= k*{[p1 * (l1 * 0.0013151 + (365 - l1)) + (1 - p1) * (l0 * 0.0025205 + (365 - l0))]/365} - {p1 * (168.19 * l1) + (1 - p1) * (113.61 * l0)}
\end{align}
$$

When $t = 2$:

$$
\begin{align}
u(e,c;t) &= nb_t = k\mu_{et} - \mu_{ct} \\
u(e,c;t) &= k*{[p2 * (l1 * 0.0013151 + (365 - l1)) + (1 - p2) * (l0 * 0.0025205 + (365 - l0))]/365} - {p2 * (168.19 * l1 + 201.47) + (1 - p2) * (113.61 * l0 + 201.47)}
\end{align}
$$

## Question 2

#### Length of Staying in Hospital

It's intuitive that the length in time is non-negative. Considering the mean length of stay in hospital for people without severe complications is 4.36 days with a standard deviation of 1.8 days, modelling using symmetric distributions (e.g. normal) may cause bias due to the allowance of negativity. Therefore, we decided to use Gamma distribution to model this quantity.

We know that
